### PR TITLE
styled headings and subheadings

### PR DESCRIPTION
**Pull request by SharonNabiryo**

### CODE REVIEW

**Comment by SharonNabiryo** [comment]
Kindly review and let me know

**Review by shagariboy — APPROVED** [review]
The dark theme toggle ball doesn't cover the moon and sun icons. Can you work on that? Good Job!

**Review by shagariboy — APPROVED** [review]

**Review by shagariboy — APPROVED** [review]

**Comment by SharonNabiryo** [comment]
sure I can do that. Thanks

**Comment by RW2023** [comment]
Fire 🔥🔥🔥🔥🔥!

recording


<details><summary>Browser metadata</summary>





```
Path:      /
Browser:   Firefox 112.0 on Windows 10
Viewport:  1536 x 600 @1.25x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-17--jsknowledge.netlify.app%2F&os=Windows&os_version=10&browser=Firefox&browser_version=112.0&resolution=1536x600&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-17--jsknowledge.netlify.app/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=642f15d42194c500080ea420&commentID=642f9a3224e80a5d264ded35&resolution=resolved)

**Review by RW2023 — APPROVED** [review]

**Pull request merged**
